import type { CategoryGroup } from "../types/learning.types";

export const LEARNING_CATEGORY_GROUPS: CategoryGroup[] = [
  {
    id: "roles",
    title: "CÂU HỎI HAY GẶP THEO VỊ TRÍ",
    titleEn: "FREQUENT QUESTIONS BY ROLE",
    items: [
      { id: "dept-frontend", label: "Frontend", labelEn: "Frontend", department: "frontend" },
      { id: "dept-backend", label: "Backend", labelEn: "Backend", department: "backend" },
      { id: "dept-data-and-messaging", label: "Database & Messaging", labelEn: "Database & Messaging", department: "data-and-messaging" },
      { id: "dept-devops", label: "DevOps & Cloud", labelEn: "DevOps & Cloud", department: "infrastructure" },
      { id: "dept-mobile", label: "Mobile Development", labelEn: "Mobile Development", department: "mobile" },
      { id: "dept-architecture", label: "System Architecture", labelEn: "System Architecture", department: "architecture" },
      { id: "dept-ai", label: "AI & Machine Learning", labelEn: "AI & Machine Learning", department: "ai-ml" },
      { id: "dept-security", label: "Security & Testing", labelEn: "Security & Testing", department: "quality-security" },
      { id: "dept-ba", label: "Business Analyst (BA)", labelEn: "Business Analyst (BA)", isNew: true, department: "business-analysis" },
      { id: "dept-career", label: "Phỏng vấn HR & Hành vi", labelEn: "HR & Behavioral Interview", department: "career" },
      { id: "dept-base", label: "Khoa học máy tính & Mạng", labelEn: "Computer Science & Networks", department: "base" },
    ],
  },
  {
    id: "frontend",
    title: "FRONTEND",
    titleEn: "FRONTEND",
    items: [
      { id: "topic-html", label: "HTML", labelEn: "HTML", topic: "html", department: "frontend" },
      { id: "topic-css", label: "CSS", labelEn: "CSS", topic: "css", department: "frontend" },
      { id: "topic-javascript", label: "JavaScript", labelEn: "JavaScript", topic: "javascript", department: "frontend" },
      { id: "topic-typescript", label: "TypeScript", labelEn: "TypeScript", topic: "typescript", department: "frontend" },
      { id: "topic-react", label: "React", labelEn: "React", topic: "react", department: "frontend" },
      { id: "topic-nextjs", label: "Next.js", labelEn: "Next.js", topic: "nextjs", department: "frontend" },
      { id: "topic-vue", label: "Vue.js", labelEn: "Vue.js", topic: "vue", department: "frontend" },
      { id: "topic-angular", label: "Angular", labelEn: "Angular", topic: "angular", department: "frontend" },
      { id: "topic-state-management", label: "State Management", labelEn: "State Management", topic: "state-management", department: "frontend" },
      { id: "topic-micro-frontend", label: "Micro-frontend", labelEn: "Micro-frontend", topic: "micro-frontend", department: "frontend" },
      { id: "topic-performance", label: "Performance", labelEn: "Performance", topic: "performance", department: "frontend" },
      { id: "topic-build-tools", label: "Build Tools", labelEn: "Build Tools", topic: "build-tools", department: "frontend" },
      { id: "topic-seo", label: "SEO", labelEn: "SEO", topic: "seo", department: "frontend" },
    ],
  },
  {
    id: "backend",
    title: "BACKEND & LẬP TRÌNH HỆ THỐNG",
    titleEn: "BACKEND & SYSTEM PROGRAMMING",
    items: [
      { id: "topic-backend-api", label: "Backend & API", labelEn: "Backend & API", topic: "backend&api", department: "backend" },
      { id: "topic-nodejs", label: "Node.js", labelEn: "Node.js", topic: "nodejs", department: "backend" },
      { id: "topic-nestjs", label: "NestJS", labelEn: "NestJS", topic: "nestjs", department: "backend" },
      { id: "topic-python", label: "Python", labelEn: "Python", topic: "python", department: "backend" },
      { id: "topic-fastapi", label: "FastAPI", labelEn: "FastAPI", topic: "fastapi", department: "backend" },
      { id: "topic-django", label: "Django", labelEn: "Django", topic: "django", department: "backend" },
      { id: "topic-java", label: "Java", labelEn: "Java", topic: "java", department: "backend" },
      { id: "topic-spring-boot", label: "Spring Boot", labelEn: "Spring Boot", topic: "spring-boot", department: "backend" },
      { id: "topic-golang", label: "Golang", labelEn: "Golang", topic: "golang", department: "backend" },
      { id: "topic-csharp", label: "C# / .NET", labelEn: "C# / .NET", topic: "csharp", department: "backend" },
      { id: "topic-cpp", label: "C++", labelEn: "C++", topic: "c++", department: "backend" },
      { id: "topic-php", label: "PHP", labelEn: "PHP", topic: "php", department: "backend" },
      { id: "topic-laravel", label: "Laravel", labelEn: "Laravel", topic: "laravel", department: "backend" },
      { id: "topic-ruby", label: "Ruby", labelEn: "Ruby", topic: "ruby", department: "backend" },
      { id: "topic-rails", label: "Ruby on Rails", labelEn: "Ruby on Rails", topic: "rails", department: "backend" },
      { id: "topic-graphql", label: "GraphQL", labelEn: "GraphQL", isNew: true, topic: "graphql", department: "backend" },
    ],
  },
  {
    id: "database",
    title: "DATABASE & DATA MESSAGING",
    titleEn: "DATABASE & DATA MESSAGING",
    items: [
      { id: "topic-database", label: "Database Tổng quan", labelEn: "Database Overview", topic: "database", department: "data-and-messaging" },
      { id: "topic-postgresql", label: "PostgreSQL", labelEn: "PostgreSQL", topic: "postgresql", department: "data-and-messaging" },
      { id: "topic-mongodb", label: "MongoDB", labelEn: "MongoDB", topic: "mongodb", department: "data-and-messaging" },
      { id: "topic-redis", label: "Redis", labelEn: "Redis", topic: "redis", department: "data-and-messaging" },
      { id: "topic-elasticsearch", label: "Elasticsearch", labelEn: "Elasticsearch", topic: "elasticsearch", department: "data-and-messaging" },
      { id: "topic-kafka", label: "Kafka", labelEn: "Kafka", topic: "kafka", department: "data-and-messaging" },
      { id: "topic-rabbitmq", label: "RabbitMQ", labelEn: "RabbitMQ", topic: "rabbitMQ", department: "data-and-messaging" },
    ],
  },
  {
    id: "devops",
    title: "DEVOPS, CLOUD & HẠ TẦNG",
    titleEn: "DEVOPS, CLOUD & INFRASTRUCTURE",
    items: [
      { id: "topic-devops-cloud", label: "DevOps & Cloud", labelEn: "DevOps & Cloud", topic: "devops-cloud", department: "infrastructure" },
      { id: "topic-docker-k8s", label: "Docker & Kubernetes", labelEn: "Docker & Kubernetes", topic: "docker&kubernetes", department: "infrastructure" },
      { id: "topic-cloud-aws", label: "Cloud & AWS", labelEn: "Cloud & AWS", topic: "cloud&aws", department: "infrastructure" },
      { id: "topic-cicd", label: "CI/CD", labelEn: "CI/CD", topic: "cicd", department: "infrastructure" },
      { id: "topic-terraform", label: "Terraform & IaC", labelEn: "Terraform & IaC", topic: "terraform&IaC", department: "infrastructure" },
      { id: "topic-git", label: "Git & Version Control", labelEn: "Git & Version Control", topic: "git", department: "infrastructure" },
    ],
  },
  {
    id: "architecture",
    title: "KIẾN TRÚC & THIẾT KẾ HỆ THỐNG",
    titleEn: "SYSTEM DESIGN & ARCHITECTURE",
    items: [
      { id: "topic-system-design", label: "System Design", labelEn: "System Design", topic: "system-design", department: "architecture" },
      { id: "topic-design-patterns", label: "Design Patterns", labelEn: "Design Patterns", topic: "design-patterns", department: "architecture" },
    ],
  },
  {
    id: "mobile",
    title: "MOBILE DEVELOPMENT",
    titleEn: "MOBILE DEVELOPMENT",
    items: [
      { id: "topic-flutter", label: "Flutter", labelEn: "Flutter", topic: "flutter", department: "mobile" },
      { id: "topic-react-native", label: "React Native", labelEn: "React Native", topic: "react-native", department: "mobile" },
      { id: "topic-android", label: "Android Native", labelEn: "Android Native", topic: "android", department: "mobile" },
    ],
  },
  {
    id: "ai-security",
    title: "AI, DATA & BẢO MẬT",
    titleEn: "AI, DATA & SECURITY",
    items: [
      { id: "topic-ai", label: "Trí tuệ nhân tạo (AI)", labelEn: "Artificial Intelligence (AI)", topic: "ai", department: "ai-ml" },
      { id: "topic-aiml", label: "Machine Learning (AI & ML)", labelEn: "Machine Learning (AI & ML)", topic: "ai&ml", department: "ai-ml" },
      { id: "topic-security", label: "Security & Bảo mật", labelEn: "Security", topic: "security", department: "quality-security" },
      { id: "topic-testing", label: "Software Testing & QA", labelEn: "Software Testing & QA", topic: "testing", department: "quality-security" },
    ],
  },
  {
    id: "others",
    title: "NỀN TẢNG KỸ THUẬT & KỸ NĂNG",
    titleEn: "FUNDAMENTALS & SKILLS",
    items: [
      { id: "topic-ba", label: "Business Analysis (BA)", labelEn: "Business Analysis (BA)", isNew: true, topic: "ba", department: "business-analysis" },
      { id: "topic-computer-network", label: "Mạng máy tính (Network)", labelEn: "Computer Networking", topic: "computer-network", department: "base" },
      { id: "topic-linux-os", label: "Linux & Hệ điều hành", labelEn: "Linux & Operating Systems", topic: "linux&os", department: "base" },
      { id: "topic-hr-behavior", label: "Phỏng vấn HR & Behavior", labelEn: "HR & Behavioral Interview", topic: "hr&behavior", department: "career" },
    ],
  },
];
