using System.Text.RegularExpressions;
using GdscSharingPlatform.Api.Controllers.Roadmaps;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace GdscSharingPlatform.Api.OpenApi;

public sealed class RoadmapOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        if (context.MethodInfo.DeclaringType is not { } type || !typeof(RoadmapApiController).IsAssignableFrom(type)) return;
        var controllerName = type.Name.EndsWith("Controller", StringComparison.Ordinal)
            ? type.Name[..^"Controller".Length] : type.Name;
        operation.Tags = [new OpenApiTag
        {
            Name = Regex.Replace(controllerName, "(?<=[a-z0-9])(?=[A-Z])", " ")
        }];
        operation.Description = "Requires an active authenticated account. Admin routes require the Admin role. "
            + "Members can read Published and Archived roadmaps; Draft and inactive content are hidden. "
            + "New roadmaps are Published. Switching to Published requires an active node. "
            + "Archived roadmaps reject new nodes, edges and resources. Errors return Problem Details with traceId and validationErrors.";
        if (context.ApiDescription.RelativePath?.EndsWith("download") == true)
        {
            operation.Responses["200"] = new OpenApiResponse
            {
                Description = "Authorized file attachment with its original filename and MIME type.",
                Content = new Dictionary<string, OpenApiMediaType>
                {
                    ["application/octet-stream"] = new() { Schema = new OpenApiSchema { Type = "string", Format = "binary" } }
                }
            };
        }
        if (operation.RequestBody?.Content.ContainsKey("multipart/form-data") == true)
            operation.Description += " Upload at most 20 MiB (deployment may configure a smaller limit). "
                + "Allowed extensions: .pdf, .png, .jpg, .jpeg, .txt, .md, .docx, .pptx, .xlsx. "
                + "Extension, MIME type and file signature must agree; text must be UTF-8. File metadata is generated by storage.";
        if (context.ApiDescription.RelativePath?.EndsWith("reorder") == true)
            operation.Description += " Body: { ids: [uuid, ...] }. Include every existing ID, including inactive entries, exactly once; array order becomes zero-based SortOrder.";
    }
}
